import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const danfofont = localFont({
	src: "fonts/Danfo-Regular-VariableFont_ELSH.ttf",
	display: "swap",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex min-h-screen flex-col items-center justify-start`}
			>
				<nav className="w-full h-[60px] px-5 flex justify-start items-center">
					<div className={`${danfofont.className} text-red-600 text-2xl`}>
						Tanush&apos;s Portfolio
					</div>
				</nav>
				{children}
			</body>
		</html>
	);
}
